<?php

    namespace Firumon\Makhzun\Seeder;

    use Firumon\Makhzun\Traits\SeederTrait;
    use Illuminate\Database\Seeder;

    class CodeSeeder extends Seeder implements SeederInterface
    {
        use SeederTrait;

        public function fields(): array
        {
            return ['code','item'];
        }

        public function records(): array
        {
            return [
                ['SETCURRENCY','settings'],
                ['SETTAXONCODE','settings'],
                ['SETPRDPRICE','settings'],
                ['SETPRIWTHTAX','settings'],

                ['OPTPRDUOM','options'],
                ['OPTCONTTYPE','options'],
                ['OPTCONTNAT','options'],
                ['OPTVCHRTYPE','options'],
                ['OPTVCHRPAYST','options'],
                ['OPTPYMTMODE','options'],
                ['OPTINVTYPE','options'],
                ['OPTINVPAYST','options'],

                ['TAXPERCENT05','taxes'],
                ['TAXPERCENT10','taxes'],
                ['TAXPERCENT12','taxes'],
                ['TAXPERCENT15','taxes'],
                ['TAXPERCENT20','taxes'],
                ['TAXPERCENT25','taxes'],
                ['TAXVAT05','taxes'],
                ['TAXVAT10','taxes'],
                ['TAXVAT12','taxes'],
                ['TAXVAT15','taxes'],
                ['TAXVAT20','taxes'],
                ['TAXVAT25','taxes'],
                ['TAXCGST25','taxes'],
                ['TAXCGST06','taxes'],
                ['TAXCGST09','taxes'],
                ['TAXCGST14','taxes'],
                ['TAXSGST25','taxes'],
                ['TAXSGST06','taxes'],
                ['TAXSGST09','taxes'],
                ['TAXSGST14','taxes'],
                ['TAXCESS01','taxes'],
                ['TAXSALES','taxes'],
                ['TAXVAT','taxes'],
                ['TAXCESS','taxes'],
                ['TAXGST05','taxes'],
                ['TAXGST12','taxes'],
                ['TAXGST18','taxes'],
                ['TAXGST28','taxes'],

                ['GRPPRDGROUP1','groups'],
                ['GRPPRDGROUP2','groups'],
                ['GRPPRDGROUP3','groups'],
                ['GRPPRDGROUP4','groups'],
                ['GRPPRDGROUP5','groups'],
                ['GRPPRDGROUP6','groups'],

                ['PRDNAME','products'],
                ['PRDCODE','products'],
                ['PRDDESC','products'],
                ['PRDUOM','products'],
                ['PRDGRP1','products'],
                ['PRDGRP2','products'],
                ['PRDGRP3','products'],
                ['PRDGRP4','products'],
                ['PRDGRP5','products'],
                ['PRDPRICE','products'],
                ['PRDSTOCK','products'],
                ['PRDSTATUS','products'],
                ['PRDIMAGE01','products'],
                ['PRDIMAGE02','products'],

                ['CONTNAME','contacts'],
                ['CONTTYPE','contacts'],
                ['CONTNATURE','contacts'],
                ['CONTPHONE','contacts'],
                ['CONTEMAIL','contacts'],
                ['CONTNOTE','contacts'],
                ['CONTDESIGNAT','contacts'],
                ['CONTCOUNTRY','contacts'],
                ['CONTSTATE','contacts'],
                ['CONTCITY','contacts'],
                ['CONTADDR','contacts'],
                ['CONTBANK','contacts'],
                ['CONTBNKBRNCH','contacts'],
                ['CONTACCNO','contacts'],
                ['CONTISFC','contacts'],
                ['CONTPARENT','contacts'],
                ['CONTSHPADDR','contacts'],
                ['CONTBILLADDR','contacts'],
                ['CONTSTATUS','contacts'],
                ['CONTIMG01','contacts'],
                ['CONTIMG02','contacts'],

                ['PONAME','purchase_orders'],
                ['PONO','purchase_orders'],
                ['POCMP','purchase_orders'],
                ['POPREPDATE','purchase_orders'],
                ['POEXPIRYDATE','purchase_orders'],
                ['POPREPBY','purchase_orders'],
                ['PONOTE','purchase_orders'],

                ['PODPRD','purchase_order_details'],
                ['PODQTY','purchase_order_details'],

                ['SSONAME','supplier_sales_orders'],
                ['SSONO','supplier_sales_orders'],
                ['SSOCMP','supplier_sales_orders'],
                ['SSODATE','supplier_sales_orders'],
                ['SSOEXPIRY','supplier_sales_orders'],
                ['SSOPREPARED','supplier_sales_orders'],
                ['SSOREFPO','supplier_sales_orders'],
                ['SSOTTLAMNT','supplier_sales_orders'],
                ['SSOTAX','supplier_sales_orders'],
                ['SSODELIEXP','supplier_sales_orders'],
                ['SSODISCOUNT','supplier_sales_orders'],
                ['SSONETPAY','supplier_sales_orders'],
                ['SSOATTACH','supplier_sales_orders'],

                ['SSODPRD','supplier_sales_order_details'],
                ['SSODRATE','supplier_sales_order_details'],
                ['SSODQTY','supplier_sales_order_details'],
                ['SSODAMNT','supplier_sales_order_details'],
                ['SSODTAX','supplier_sales_order_details'],
                ['SSODDISCOUNT','supplier_sales_order_details'],
                ['SSODTOTAL','supplier_sales_order_details'],

                ['PURNAME','purchases'],
                ['PURNO','purchases'],
                ['PURCMP','purchases'],
                ['PURDATE','purchases'],
                ['PURSHPADDR','purchases'],
                ['PURBILLADDR','purchases'],
                ['PURAMOUNT','purchases'],
                ['PURTAX','purchases'],
                ['PURSHPEXP','purchases'],
                ['PURDISC','purchases'],
                ['PURRNDOFF','purchases'],
                ['PURNETPAY','purchases'],
                ['PURREFPO','purchases'],
                ['PURREFSSO','purchases'],
                ['PURNOTES','purchases'],
                ['PURINVATTACH','purchases'],

                ['PURDPRD','purchase_details'],
                ['PURDRATE','purchase_details'],
                ['PURDQTY','purchase_details'],
                ['PURDTOTAL','purchase_details'],
                ['PURDTAX','purchase_details'],
                ['PURDDISCOUNT','purchase_details'],
                ['PURDNETPAY','purchase_details'],

                ['VCHRNO','vouchers'],
                ['VCHRDATE','vouchers'],
                ['VCHRTYPE','vouchers'],
                ['VCHRAMOUNT','vouchers'],
                ['VCHRREFPUR','vouchers'],
                ['VCHRNOTE','vouchers'],
                ['VCHRPAYSTAT','vouchers'],

                ['PYMTNO','payments'],
                ['PYMTDATE','payments'],
                ['PYMTREFVCHR','payments'],
                ['PYMTMODE','payments'],
                ['PYMTAMOUNT','payments'],
                ['PYMTCHQNO','payments'],
                ['PYMTCHQDATE','payments'],
                ['PYMTCHQBANK','payments'],
                ['PYMTNOTE','payments'],
                ['PYMTRECATTCH','payments'],
                ['PYMTVCHRATTH','payments'],

                ['CPONAME','customer_purchase_orders'],
                ['CPONO','customer_purchase_orders'],
                ['CPOCMP','customer_purchase_orders'],
                ['CPODATE','customer_purchase_orders'],
                ['CPOEXPIRY','customer_purchase_orders'],
                ['CPOPREPBY','customer_purchase_orders'],
                ['CPODELIADDR','customer_purchase_orders'],
                ['CPOBILLADDR','customer_purchase_orders'],
                ['CPOCUSTRMKRS','customer_purchase_orders'],
                ['CPONOTE','customer_purchase_orders'],

                ['CPODOCATTACH','customer_purchase_orders'],
                ['CPODPRD','customer_purchase_order_details'],
                ['CPODQTY','customer_purchase_order_details'],

                ['SONAME','sales_orders'],
                ['SONO','sales_orders'],
                ['SOCMP','sales_orders'],
                ['SODATE','sales_orders'],
                ['SOEXPIRY','sales_orders'],
                ['SOPREPBY','sales_orders'],
                ['SODELIADDR','sales_orders'],
                ['SOBILLADDR','sales_orders'],
                ['SOTOTAL','sales_orders'],
                ['SOTAX','sales_orders'],
                ['SODELICHRGE','sales_orders'],
                ['SODSCOUNT','sales_orders'],
                ['SORNDOFF','sales_orders'],
                ['SOOTHCHRGE','sales_orders'],
                ['SONETPAY','sales_orders'],

                ['SODPRD','sales_order_details'],
                ['SODRATE','sales_order_details'],
                ['SODQTY','sales_order_details'],
                ['SODAMOUNT','sales_order_details'],
                ['SODTAX','sales_order_details'],
                ['SODDISCOUNT','sales_order_details'],
                ['SODTOTAL','sales_order_details'],

                ['SLSNAME','sales'],
                ['SLSNO','sales'],
                ['SLSCMP','sales'],
                ['SLSDATE','sales'],
                ['SLSREFSO','sales'],
                ['SLSREFCPO','sales'],
                ['SLSDELIADDR','sales'],
                ['SLSBILLADDR','sales'],
                ['SLSTOTAL','sales'],
                ['SLSTAX','sales'],
                ['SLSDELICHRGE','sales'],
                ['SLSDISCOUNT','sales'],
                ['SLSRNDOFF','sales'],
                ['SLSOTHCHRGE','sales'],
                ['SLSNETPAY','sales'],

                ['SLSDPRD','sales_details'],
                ['SLSDRATE','sales_details'],
                ['SLSDQTY','sales_details'],
                ['SLSDAMOUNT','sales_details'],
                ['SLSDTAX','sales_details'],
                ['SLSDDISCOUNT','sales_details'],
                ['SLSDTOTAL','sales_details'],

                ['INVNO','invoices'],
                ['INVDATE','invoices'],
                ['INVTYPE','invoices'],
                ['INVAMOUNT','invoices'],
                ['INVREFSLS','invoices'],
                ['INVNOTE','invoices'],
                ['INVPAYSTAT','invoices'],

                ['RCPTNO','receipts'],
                ['RCPTDATE','receipts'],
                ['RCPTREFVCHR','receipts'],
                ['RCPTMODE','receipts'],
                ['RCPTAMOUNT','receipts'],
                ['RCPTCHQNO','receipts'],
                ['RCPTCHQDATE','receipts'],
                ['RCPTCHQBANK','receipts'],
                ['RCPTNOTE','receipts']
            ];
        }

    }
